import { NextResponse } from "next/server";

export async function POST(request) {
  return NextResponse.json(
    {
      success: true,
      message: `Providers Fetchign Success`,
      data: [
        {
          id: 21,
          title: `Home Cleaner`,
          available: true,
          rating: 4.5,
          order_complted: 10,
          banner: ``,
          logo: ``,
          address: `Schwarzenberg, Switzerland, 6867`,
          description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero maxime in eum labore officiis id. Expedita quaerat molestias voluptatum nisi incidunt blanditiis quidem dolorem quisquam possimus esse accusantium voluptatibus debitis, corrupti repellat quam numquam aliquam voluptates, quis eveniet fugiat itaque earum eos reprehenderit laborum. Accusantium quo numquam eveniet eos quod!`,
          slug: `home-cleaner`,
        },
        {
          id: 22,
          title: `Laundry Cleaner`,
          available: true,
          rating: 4.0,
          order_complted: 7,
          banner: ``,
          logo: ``,
          address: `lorem, Switzerland, 6867`,
          description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero maxime in eum labore officiis id. Expedita quaerat molestias voluptatum nisi incidunt blanditiis quidem dolorem quisquam possimus esse accusantium voluptatibus debitis, corrupti repellat quam numquam aliquam voluptates, quis eveniet fugiat itaque earum eos reprehenderit laborum. Accusantium quo numquam eveniet eos quod!`,
          slug: `laundry-cleaner`,
        },
        {
          id: 23,
          title: `Full Service Cleaner`,
          available: true,
          rating: 3.8,
          order_complted: 10,
          banner: ``,
          logo: ``,
          address: `Schwarzenberg, Switzerland, 6867`,
          description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero maxime in eum labore officiis id. Expedita quaerat molestias voluptatum nisi incidunt blanditiis quidem dolorem quisquam possimus esse accusantium voluptatibus debitis, corrupti repellat quam numquam aliquam voluptates, quis eveniet fugiat itaque earum eos reprehenderit laborum. Accusantium quo numquam eveniet eos quod!`,
          slug: `full-service-cleaner`,
        },
        {
          id: 24,
          title: `New Barber`,
          available: true,
          rating: 4.0,
          order_complted: 58,
          banner: ``,
          logo: ``,
          address: `Schwarzenberg, Switzerland, 6867`,
          description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero maxime in eum labore officiis id. Expedita quaerat molestias voluptatum nisi incidunt blanditiis quidem dolorem quisquam possimus esse accusantium voluptatibus debitis, corrupti repellat quam numquam aliquam voluptates, quis eveniet fugiat itaque earum eos reprehenderit laborum. Accusantium quo numquam eveniet eos quod!`,
          slug: `new-barber`,
        },
        {
          id: 25,
          title: `Electric`,
          available: true,
          rating: 4.3,
          order_complted: 49,
          banner: ``,
          logo: ``,
          address: `Schwarzenberg, Switzerland, 6867`,
          description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero maxime in eum labore officiis id. Expedita quaerat molestias voluptatum nisi incidunt blanditiis quidem dolorem quisquam possimus esse accusantium voluptatibus debitis, corrupti repellat quam numquam aliquam voluptates, quis eveniet fugiat itaque earum eos reprehenderit laborum. Accusantium quo numquam eveniet eos quod!`,
          slug: `electric`,
        },
        {
          id: 26,
          title: `Pest Control`,
          available: true,
          rating: 4.0,
          order_complted: 23,
          banner: ``,
          logo: ``,
          address: `Schwarzenberg, Switzerland, 6867`,
          description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero maxime in eum labore officiis id. Expedita quaerat molestias voluptatum nisi incidunt blanditiis quidem dolorem quisquam possimus esse accusantium voluptatibus debitis, corrupti repellat quam numquam aliquam voluptates, quis eveniet fugiat itaque earum eos reprehenderit laborum. Accusantium quo numquam eveniet eos quod!`,
          slug: `pest-control`,
        },
        {
          id: 27,
          title: `testing plumbing`,
          available: true,
          rating: 3.9,
          order_complted: 30,
          banner: ``,
          logo: ``,
          address: `Schwarzenberg, Switzerland, 6867`,
          description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero maxime in eum labore officiis id. Expedita quaerat molestias voluptatum nisi incidunt blanditiis quidem dolorem quisquam possimus esse accusantium voluptatibus debitis, corrupti repellat quam numquam aliquam voluptates, quis eveniet fugiat itaque earum eos reprehenderit laborum. Accusantium quo numquam eveniet eos quod!`,
          slug: `testing-plumbing`,
        },
        {
          id: 28,
          title: `Kitchen Expert`,
          available: true,
          rating: 4.8,
          order_complted: 48,
          banner: ``,
          logo: ``,
          address: `Schwarzenberg, America, 6867`,
          description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero maxime in eum labore officiis id. Expedita quaerat molestias voluptatum nisi incidunt blanditiis quidem dolorem quisquam possimus esse accusantium voluptatibus debitis, corrupti repellat quam numquam aliquam voluptates, quis eveniet fugiat itaque earum eos reprehenderit laborum. Accusantium quo numquam eveniet eos quod!`,
          slug: `kitchen-expert`,
        },
        {
          id: 29,
          title: `Car Provider`,
          available: true,
          rating: 4.0,
          order_complted: 18,
          banner: ``,
          logo: ``,
          address: `Schwarzenberg, Switzerland, 6867`,
          description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero maxime in eum labore officiis id. Expedita quaerat molestias voluptatum nisi incidunt blanditiis quidem dolorem quisquam possimus esse accusantium voluptatibus debitis, corrupti repellat quam numquam aliquam voluptates, quis eveniet fugiat itaque earum eos reprehenderit laborum. Accusantium quo numquam eveniet eos quod!`,
          slug: `car-provider`,
        },
        {
          id: 30,
          title: `Your helper`,
          available: true,
          rating: 4.2,
          order_complted: 100,
          banner: ``,
          logo: ``,
          address: `Schwarzenberg, Switzerland, 6867`,
          description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero maxime in eum labore officiis id. Expedita quaerat molestias voluptatum nisi incidunt blanditiis quidem dolorem quisquam possimus esse accusantium voluptatibus debitis, corrupti repellat quam numquam aliquam voluptates, quis eveniet fugiat itaque earum eos reprehenderit laborum. Accusantium quo numquam eveniet eos quod!`,
          slug: `your-helper`,
        },
      ],
    },
    {
      status: 200,
    }
  );
}
