import { NextResponse } from "next/server";

export async function POST(request) {
  return NextResponse.json(
    {
      success: true,
      message: `Providers Fetchign Success`,
      data: [
        {
          id: 21,
          title: `Home Cleaner`,
          available: true,
          rating: 4.5,
          order_complted: 10,
          banner: `https://media.istockphoto.com/id/863454098/photo/woman-cleaning-with-a-spray-detergent.webp?s=2048x2048&w=is&k=20&c=v-y7ZrJRnJUE4CZYn9-jP8hnJj39dzMYA0qAVK0m5Zo=`,
          logo: `https://media.istockphoto.com/id/1200097176/vector/cleaning-service-vector-icon.webp?s=2048x2048&w=is&k=20&c=PkoZzpDaqCeb_b56674CqKbj2PY4PO0BHyOU6Xf17Pg=`,
          address: `Schwarzenberg, Switzerland, 6867`,
          description: `We offer a comprehensive range of home services to cater to all your needs. Whether you're facing plumbing issues, electrical problems, or require general maintenance, our skilled technicians are here to help. We understand that your home is your sanctuary, and we are committed to ensuring it remains in top condition.At our home service company, we believe in a customer-centric approach. Your satisfaction is our ultimate goal. We listen to your needs, provide transparent solutions, and ensure that the work is completed to your satisfaction. We take pride in building lasting relationships with our clients`,
          slug: `home-cleaner`,
        },
        {
          id: 22,
          title: `Laundry Cleaner`,
          available: true,
          rating: 4.0,
          order_complted: 7,
          banner: `https://media.istockphoto.com/id/1134696879/photo/laundry-room-with-a-washing-machine.webp?s=2048x2048&w=is&k=20&c=7sCJmezXwRdI2zr_Zd25D5SAhYpVkVMHdFXHztvCoyI=`,
          logo: `https://media.istockphoto.com/id/1286932939/vector/washing-and-drying-clothes-design-laundry-room-with-a-washing-machine-and-laundry-basket.webp?s=2048x2048&w=is&k=20&c=kAB3-YKx7sCCdjE6zgcR0WsjvKofhEhG35QRTskE2SM=`,
          address: `lorem, Switzerland, 6867`,
          description: `As your comprehensive plumbing service provider, we offer a wide range of plumbing solutions to meet your residential and commercial needs. Our services encompass everything from routine plumbing maintenance to emergency repairs. We understand the crucial role plumbing plays in your daily life, and we're here to keep it running smoothly.We offer competitive and transparent pricing for our plumbing services. You'll receive clear estimates and invoices, so you know exactly what you're paying for. Our goal is to provide cost-effective solutions without compromising on the quality of our work.`,
          slug: `laundry-cleaner`,
        },
        {
          id: 23,
          title: `Full Service Cleaner`,
          available: true,
          rating: 3.8,
          order_complted: 10,
          banner: `https://media.istockphoto.com/id/1224850161/photo/a-middle-aged-woman-tidies-up-her-cupboard-in-the-kitchen-and-reorganizes-everything.webp?s=2048x2048&w=is&k=20&c=FpaMzY_vy4Klg9fd6qM5f5C7TzCFVQpW0H9F29GovHg=`,
          logo: `https://media.istockphoto.com/id/1272687883/vector/stay-home-concept-home-love-heart-icon.webp?s=2048x2048&w=is&k=20&c=D71vWi6UGctpY7DAOX14FNcQ7o_Syp-VJOgWAfSglyM=`,
          address: `Schwarzenberg, Switzerland, 6867`,
          description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero maxime in eum labore officiis id. Expedita quaerat molestias voluptatum nisi incidunt blanditiis quidem dolorem quisquam possimus esse accusantium voluptatibus debitis, corrupti repellat quam numquam aliquam voluptates, quis eveniet fugiat itaque earum eos reprehenderit laborum. Accusantium quo numquam eveniet eos quod!`,
          slug: `full-service-cleaner`,
        },
        {
          id: 24,
          title: `New Barber`,
          available: true,
          rating: 4.0,
          order_complted: 58,
          banner: `https://media.istockphoto.com/id/640274128/photo/barber-using-scissors-and-comb.webp?s=2048x2048&w=is&k=20&c=JfHrRbaY4VFXB3S3e-ZdNneYAoakxw0E3OK8egtEYPQ=`,
          logo: `https://media.istockphoto.com/id/1387780759/vector/barbershop-vector.webp?s=2048x2048&w=is&k=20&c=L2EMZicbO8KMMVMs0pM48pO9Jk1r01FI9xTOFpeXX8g=`,
          address: `Schwarzenberg, Switzerland, 6867`,
          description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero maxime in eum labore officiis id. Expedita quaerat molestias voluptatum nisi incidunt blanditiis quidem dolorem quisquam possimus esse accusantium voluptatibus debitis, corrupti repellat quam numquam aliquam voluptates, quis eveniet fugiat itaque earum eos reprehenderit laborum. Accusantium quo numquam eveniet eos quod!`,
          slug: `new-barber`,
        },
        {
          id: 25,
          title: `Electric`,
          available: true,
          rating: 4.3,
          order_complted: 49,
          banner: `https://media.istockphoto.com/id/1049775258/photo/smiling-handsome-electrician-repairing-electrical-box-with-pliers-in-corridor-and-looking-at.webp?s=2048x2048&w=is&k=20&c=2MfJrDttEgalp7h1BQNUi8XZSgjKUH0dONnALk8QgN4=`,
          logo: `https://media.istockphoto.com/id/1032150246/vector/power-lightning-logo-icon-vector-electric-fast-thunder-bolt-symbol-isolated-on-transparent.webp?s=2048x2048&w=is&k=20&c=lSNuZ05BmYDg1LyIFqC_m-xqWLhGH6v2eVKk8VtFgFM=`,
          address: `Schwarzenberg, Switzerland, 6867`,
          description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero maxime in eum labore officiis id. Expedita quaerat molestias voluptatum nisi incidunt blanditiis quidem dolorem quisquam possimus esse accusantium voluptatibus debitis, corrupti repellat quam numquam aliquam voluptates, quis eveniet fugiat itaque earum eos reprehenderit laborum. Accusantium quo numquam eveniet eos quod!`,
          slug: `electric`,
        },
        {
          id: 26,
          title: `Pest Control`,
          available: true,
          rating: 4.0,
          order_complted: 23,
          banner: `https://media.istockphoto.com/id/1212787021/photo/exterminators-in-warehouse-spraying-pesticides-with-sprayer.webp?s=2048x2048&w=is&k=20&c=MMilsZf224hsa8EOp5S39OASvofqyIozs-3MxisOLqA=`,
          logo: `https://media.istockphoto.com/id/1448695751/vector/pest-control-cockroach-logo-design-vector.webp?s=2048x2048&w=is&k=20&c=vqRpq2xA8gDaOCFmV37pxEELYk1Bw7emmiGTpOofkPQ=`,
          address: `Schwarzenberg, Switzerland, 6867`,
          description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero maxime in eum labore officiis id. Expedita quaerat molestias voluptatum nisi incidunt blanditiis quidem dolorem quisquam possimus esse accusantium voluptatibus debitis, corrupti repellat quam numquam aliquam voluptates, quis eveniet fugiat itaque earum eos reprehenderit laborum. Accusantium quo numquam eveniet eos quod!`,
          slug: `pest-control`,
        },
        {
          id: 27,
          title: `testing plumbing`,
          available: true,
          rating: 3.9,
          order_complted: 30,
          banner: `https://media.istockphoto.com/id/1339613829/photo/plumber-at-work-in-a-bathroom-plumbing-repair-service-assemble-and-install-concept.webp?s=2048x2048&w=is&k=20&c=VtlTqDmKRNb63hSsulMTZnxpH9fkMitsqapsMfkEAkw=`,
          logo: `https://media.istockphoto.com/id/1026488930/vector/plumbing-water-with-initial-letter-p-logo-design-template.webp?s=2048x2048&w=is&k=20&c=yYj3mpKDNXoAW6r9ASyjbPaNRCMoLo7h5q61w3QPR9g=`,
          address: `Schwarzenberg, Switzerland, 6867`,
          description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero maxime in eum labore officiis id. Expedita quaerat molestias voluptatum nisi incidunt blanditiis quidem dolorem quisquam possimus esse accusantium voluptatibus debitis, corrupti repellat quam numquam aliquam voluptates, quis eveniet fugiat itaque earum eos reprehenderit laborum. Accusantium quo numquam eveniet eos quod!`,
          slug: `testing-plumbing`,
        },
        {
          id: 28,
          title: `Kitchen Expert`,
          available: true,
          rating: 4.8,
          order_complted: 48,
          banner: `https://media.istockphoto.com/id/1137069388/photo/woman-cleaning-kitchen-counter.webp?s=2048x2048&w=is&k=20&c=7km4TURZeBNmFfw_75tHEE1J14X6FqN17mrTOGm4wK8=`,
          logo: `https://media.istockphoto.com/id/1148805492/vector/professional-cleaning-company-logo-design.webp?s=2048x2048&w=is&k=20&c=wJDBnKwoaK9Iyc9hUZv7-YUDMiYsL9malXa2nm2Kpe0=`,
          address: `Schwarzenberg, America, 6867`,
          description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero maxime in eum labore officiis id. Expedita quaerat molestias voluptatum nisi incidunt blanditiis quidem dolorem quisquam possimus esse accusantium voluptatibus debitis, corrupti repellat quam numquam aliquam voluptates, quis eveniet fugiat itaque earum eos reprehenderit laborum. Accusantium quo numquam eveniet eos quod!`,
          slug: `kitchen-expert`,
        },
        {
          id: 29,
          title: `Car Provider`,
          available: true,
          rating: 4.0,
          order_complted: 18,
          banner: `https://media.istockphoto.com/id/1273682054/photo/car-service-worker-applying-nano-coating-on-a-car-detail.webp?s=2048x2048&w=is&k=20&c=6kkQ_RwFA0r56K0EHJETUot2VSvNVsquwtYbwT8xk6E=`,
          logo: `https://media.istockphoto.com/id/1036660952/vector/auto-service-sign-car-repair-logo-eps.webp?s=2048x2048&w=is&k=20&c=VWxhPgt1o_I6lWxdn9231_UFWVPX3r8WDoZd1nneX0Y=`,
          address: `Schwarzenberg, Switzerland, 6867`,
          description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero maxime in eum labore officiis id. Expedita quaerat molestias voluptatum nisi incidunt blanditiis quidem dolorem quisquam possimus esse accusantium voluptatibus debitis, corrupti repellat quam numquam aliquam voluptates, quis eveniet fugiat itaque earum eos reprehenderit laborum. Accusantium quo numquam eveniet eos quod!`,
          slug: `car-provider`,
        },
        // {
        //   id: 30,
        //   title: `Your helper`,
        //   available: true,
        //   rating: 4.2,
        //   order_complted: 100,
        //   banner: ``,
        //   logo: ``,
        //   address: `Schwarzenberg, Switzerland, 6867`,
        //   description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero maxime in eum labore officiis id. Expedita quaerat molestias voluptatum nisi incidunt blanditiis quidem dolorem quisquam possimus esse accusantium voluptatibus debitis, corrupti repellat quam numquam aliquam voluptates, quis eveniet fugiat itaque earum eos reprehenderit laborum. Accusantium quo numquam eveniet eos quod!`,
        //   slug: `your-helper`,
        // },
      ],
    },
    {
      status: 200,
    }
  );
}
